// Generated by lsc from core.verified.ts

datatype Edge = Edge(source: string, target: string)

// ── Reachability spec + proof scaffolding (hand-written) ───────────────────────────
// Additions only: the `method` bodies below are generated verbatim; predicates,
// lemmas, invariants, decreases and asserts are the hand-written proof. The
// reachability machinery is reused from the xyflow cycle-gate case study.

predicate hasEdge(edges: seq<Edge>, a: string, b: string)
{
  exists i :: 0 <= i < |edges| && edges[i].source == a && edges[i].target == b
}

// A path is a non-empty id-sequence linked by edges. `reach` is reflexive — the
// one-element path witnesses `from ->* from` — matching canReach's reflexive seed.
ghost predicate isPath(edges: seq<Edge>, p: seq<string>)
{
  forall i :: 0 <= i < |p| - 1 ==> hasEdge(edges, p[i], p[i + 1])
}
ghost predicate reach(edges: seq<Edge>, from: string, to: string)
{
  exists p :: |p| >= 1 && p[0] == from && p[|p| - 1] == to && isPath(edges, p)
}

lemma ReachRefl(edges: seq<Edge>, n: string)
  ensures reach(edges, n, n)
{
  assert isPath(edges, [n]);   // witness: the one-element path
}

// Path extension: a path to `mid` followed by an edge mid->next reaches `next`.
lemma ReachExtend(edges: seq<Edge>, from: string, mid: string, next: string)
  requires reach(edges, from, mid)
  requires hasEdge(edges, mid, next)
  ensures reach(edges, from, next)
{
  var p :| |p| >= 1 && p[0] == from && p[|p| - 1] == mid && isPath(edges, p);
  var q := p + [next];
  forall i | 0 <= i < |q| - 1 ensures hasEdge(edges, q[i], q[i + 1]) {
    if i < |p| - 1 {
      assert q[i] == p[i] && q[i + 1] == p[i + 1];
    } else {
      assert q[i] == mid && q[i + 1] == next;
    }
  }
  assert q[0] == from && q[|q| - 1] == next && isPath(edges, q);
}

// A single edge is a (reflexive) reachability — the base of `Domination`.
lemma HasEdgeReach(edges: seq<Edge>, a: string, b: string)
  requires hasEdge(edges, a, b)
  ensures reach(edges, a, b)
{
  assert isPath(edges, [a, b]);
}

// Elements of a filtered sequence come from the original sequence.
lemma FilterIn(f: (Edge ~> bool), xs: seq<Edge>, y: Edge)
  requires forall i :: 0 <= i < |xs| ==> f.requires(xs[i])
  requires y in Std.Collections.Seq.Filter(f, xs)
  ensures y in xs
  decreases |xs|
{
  reveal Std.Collections.Seq.Filter();
  if |xs| > 0 && !(y == xs[0] && f(xs[0])) {
    FilterIn(f, xs[1..], y);
  }
}

// Universe of ids the search can encounter: the source plus all edge endpoints.
ghost function nodeUniverse(edges: seq<Edge>, from: string): set<string>
{
  {from} + (set i | 0 <= i < |edges| :: edges[i].source) + (set i | 0 <= i < |edges| :: edges[i].target)
}

// Forward filter membership: an element satisfying the predicate lands in the result.
lemma FilterContains(f: (Edge ~> bool), xs: seq<Edge>, i: nat)
  requires forall k :: 0 <= k < |xs| ==> f.requires(xs[k])
  requires i < |xs| && f(xs[i])
  ensures xs[i] in Std.Collections.Seq.Filter(f, xs)
  decreases |xs|
{
  reveal Std.Collections.Seq.Filter();
  if i > 0 {
    FilterContains(f, xs[1..], i - 1);
  }
}

// In a visited-set closed under edges, every node of a path from a visited start
// is itself visited (induction along the path prefix).
lemma PathInVisited(edges: seq<Edge>, visited: set<string>, p: seq<string>, k: nat)
  requires isPath(edges, p) && |p| >= 1 && p[0] in visited
  requires forall x :: x in visited ==> forall t :: hasEdge(edges, x, t) ==> t in visited
  requires k < |p|
  ensures p[k] in visited
  decreases k
{
  if k > 0 {
    PathInVisited(edges, visited, p, k - 1);
    assert hasEdge(edges, p[k - 1], p[k]);
  }
}

lemma ClosedReachable(edges: seq<Edge>, from: string, visited: set<string>, y: string)
  requires from in visited
  requires forall x :: x in visited ==> forall t :: hasEdge(edges, x, t) ==> t in visited
  requires reach(edges, from, y)
  ensures y in visited
{
  var p :| |p| >= 1 && p[0] == from && p[|p| - 1] == y && isPath(edges, p);
  PathInVisited(edges, visited, p, |p| - 1);
}

// ── canReach: decides reach EXACTLY (sound + complete + terminating) ────────────────
method canReach(edges: seq<Edge>, from: string, to: string) returns (res: bool)
  ensures res ==> reach(edges, from, to)        // soundness
  ensures reach(edges, from, to) ==> res         // completeness
{
  var frontier := [from];
  var visited: seq<string> := [];
  ghost var vset: set<string> := {};   // mirror of `visited` for exact cardinality
  ReachRefl(edges, from);
  while (|frontier| > 0)
    invariant forall x :: x in frontier ==> reach(edges, from, x)
    invariant forall x :: x in frontier ==> x in nodeUniverse(edges, from)
    invariant forall x :: x in vset <==> x in visited
    invariant vset <= nodeUniverse(edges, from)
    // completeness: `from` stays in the search front, `to` is never marked visited,
    // and every visited node's successors are already visited or still queued.
    invariant from in vset || from in frontier
    invariant to !in vset
    invariant forall x :: x in vset ==> forall t :: hasEdge(edges, x, t) ==> (t in vset || t in frontier)
    decreases |nodeUniverse(edges, from) - vset|, |frontier|
  {
    var cur := frontier[0];
    assert cur in nodeUniverse(edges, from);   // cur in frontier ⊆ universe
    frontier := frontier[1..];
    if (cur == to) {
      return true;
    }
    if !((cur in visited)) {
      assert cur in nodeUniverse(edges, from) - vset;   // ⇒ the difference strictly shrinks
      visited := (visited + [cur]);
      vset := vset + {cur};                    // cur ∉ vset (guard) ⇒ |universe - vset| drops by 1
      var succ := Std.Collections.Seq.Map((e: Edge) => e.target, Std.Collections.Seq.Filter((e: Edge) => (e.source == cur), edges));
      // succ elements are targets of cur's out-edges: reachable, and in the universe.
      forall x | x in succ
        ensures reach(edges, from, x) && x in nodeUniverse(edges, from)
      {
        var filtered := Std.Collections.Seq.Filter((e: Edge) => (e.source == cur), edges);
        var j :| 0 <= j < |succ| && succ[j] == x;
        assert filtered[j].source == cur && filtered[j].target == x;
        FilterIn((e: Edge) => (e.source == cur), edges, filtered[j]);
        assert hasEdge(edges, cur, x);
        ReachExtend(edges, from, cur, x);
      }
      // succ contains EVERY out-neighbour of cur — keeps the closure invariant.
      forall t | hasEdge(edges, cur, t)
        ensures t in succ
      {
        var filtered := Std.Collections.Seq.Filter((e: Edge) => (e.source == cur), edges);
        var i :| 0 <= i < |edges| && edges[i].source == cur && edges[i].target == t;
        FilterContains((e: Edge) => (e.source == cur), edges, i);
        var j :| 0 <= j < |filtered| && filtered[j] == edges[i];
        assert succ[j] == filtered[j].target == t;
      }
      frontier := (frontier + succ);
    }
  }
  // frontier is empty ⇒ vset is closed under edges and contains `from`. A path
  // from->*to would then force `to in vset`, contradicting `to !in vset`.
  assert frontier == [];
  assert from in vset;
  if reach(edges, from, to) {
    assert forall x :: x in vset ==> forall t :: hasEdge(edges, x, t) ==> t in vset;
    ClosedReachable(edges, from, vset, to);
  }
  return false;
}

// ── reachesAny: reach to a SET, decided exactly ────────────────────────────────────
method reachesAny(edges: seq<Edge>, from: string, sinks: seq<string>) returns (res: bool)
  ensures res ==> exists j :: 0 <= j < |sinks| && reach(edges, from, sinks[j])     // soundness
  ensures (exists j :: 0 <= j < |sinks| && reach(edges, from, sinks[j])) ==> res    // completeness
{
  var i := 0;
  while (i < |sinks|)
    invariant 0 <= i <= |sinks|
    invariant forall k :: 0 <= k < i ==> !reach(edges, from, sinks[k])
    decreases |sinks| - i
  {
    var i_t0 := canReach(edges, from, sinks[i]);
    if i_t0 {
      assert reach(edges, from, sinks[i]);     // canReach sound ⇒ witness j = i
      return true;
    }
    assert !reach(edges, from, sinks[i]);      // canReach complete ⇒ no path to sinks[i]
    i := (i + 1);
  }
  return false;
}

// ── violates: decide a forbidden-reach constraint exactly ───────────────────────────
// res ⟺ some `sources` module reaches some `sinks` module (through any chain).
method violates(edges: seq<Edge>, sources: seq<string>, sinks: seq<string>) returns (res: bool)
  ensures res ==> exists i, j :: 0 <= i < |sources| && 0 <= j < |sinks| && reach(edges, sources[i], sinks[j])
  ensures (exists i, j :: 0 <= i < |sources| && 0 <= j < |sinks| && reach(edges, sources[i], sinks[j])) ==> res
{
  var i := 0;
  while (i < |sources|)
    invariant 0 <= i <= |sources|
    invariant forall ip, j :: 0 <= ip < i && 0 <= j < |sinks| ==> !reach(edges, sources[ip], sinks[j])
    decreases |sources| - i
  {
    var i_t1 := reachesAny(edges, sources[i], sinks);
    if i_t1 {
      ghost var j :| 0 <= j < |sinks| && reach(edges, sources[i], sinks[j]);   // from reachesAny soundness
      assert 0 <= i < |sources| && 0 <= j < |sinks| && reach(edges, sources[i], sinks[j]);
      return true;
    }
    assert forall j :: 0 <= j < |sinks| ==> !reach(edges, sources[i], sinks[j]);   // reachesAny completeness
    i := (i + 1);
  }
  return false;
}

// ── The headline meta-theorem: we STRICTLY DOMINATE one-hop checking ────────────────
// `directViolation` is what every incumbent linter decides: a DIRECT source→sink
// import edge. `reachViolation` is the true property `violates` decides: a source
// REACHES a sink through any chain.

ghost predicate directViolation(edges: seq<Edge>, sources: seq<string>, sinks: seq<string>)
{
  exists i, j :: 0 <= i < |sources| && 0 <= j < |sinks| && hasEdge(edges, sources[i], sinks[j])
}

ghost predicate reachViolation(edges: seq<Edge>, sources: seq<string>, sinks: seq<string>)
{
  exists i, j :: 0 <= i < |sources| && 0 <= j < |sinks| && reach(edges, sources[i], sinks[j])
}

// DOMINATION: every direct violation is a real (reach) violation — we never miss
// what the cheap one-hop check catches.
lemma Domination(edges: seq<Edge>, sources: seq<string>, sinks: seq<string>)
  requires directViolation(edges, sources, sinks)
  ensures reachViolation(edges, sources, sinks)
{
  var i, j :| 0 <= i < |sources| && 0 <= j < |sinks| && hasEdge(edges, sources[i], sinks[j]);
  HasEdgeReach(edges, sources[i], sinks[j]);   // reach(sources[i], sinks[j])
}

// STRICTNESS: there is a graph where a reach-violation EXISTS but no direct
// violation does — the laundered path the one-hop check provably misses.
// Witness: ui → svc → db, forbidding ui ⇝ db. There is no direct ui → db edge.
lemma Strictness()
  ensures exists edges: seq<Edge>, sources: seq<string>, sinks: seq<string> ::
            reachViolation(edges, sources, sinks) && !directViolation(edges, sources, sinks)
{
  var edges := [Edge("ui", "svc"), Edge("svc", "db")];
  var sources := ["ui"];
  var sinks := ["db"];
  assert edges[0] == Edge("ui", "svc") && edges[1] == Edge("svc", "db");
  assert hasEdge(edges, "ui", "svc");          // witnessed by index 0
  assert hasEdge(edges, "svc", "db");          // witnessed by index 1
  ReachRefl(edges, "ui");
  ReachExtend(edges, "ui", "ui", "svc");       // reach(ui, svc)
  ReachExtend(edges, "ui", "svc", "db");       // reach(ui, db) — the 2-hop laundered path
  // No DIRECT ui → db edge: neither of the two edges is ui → db.
  forall k | 0 <= k < |edges| ensures !(edges[k].source == "ui" && edges[k].target == "db") {}
  assert !hasEdge(edges, "ui", "db");
  assert reachViolation(edges, sources, sinks) && !directViolation(edges, sources, sinks);
}
