// Generated by lsc from core.verified.ts

datatype Edge = Edge(source: string, target: string)

// ── Surfaced meta-theorems (statements in core.verified.ts; proofs here). Placed
// before the methods to match generator order; they reference predicates/lemmas
// defined further below (Dafny resolves names globally). ──────────────────────────

// DOMINATION: every direct violation is a real (reach) violation — we never miss
// what the cheap one-hop check catches.
function domination(edges: seq<Edge>, sources: seq<string>, sinks: seq<string>): bool
  requires directViolation(edges, sources, sinks)
{
  true
}

lemma domination_ensures(edges: seq<Edge>, sources: seq<string>, sinks: seq<string>)
  requires directViolation(edges, sources, sinks)
  ensures reachViolation(edges, sources, sinks)
{
  var i, j :| 0 <= i < |sources| && 0 <= j < |sinks| && hasEdge(edges, sources[i], sinks[j]);
  HasEdgeReach(edges, sources[i], sinks[j]);   // reach(sources[i], sinks[j])
}

// STRICTNESS witness: ui → svc → db, forbidding ui ⇝ db. No direct ui → db edge.
function strictnessEdges(): seq<Edge>
{
  [Edge("ui", "svc"), Edge("svc", "db")]
}

function strictness(): bool
{
  true
}

// On that witness a reach-violation EXISTS but no direct violation does — the
// laundered path the one-hop check provably misses.
lemma strictness_ensures()
  ensures reachViolation(strictnessEdges(), ["ui"], ["db"])
  ensures !(directViolation(strictnessEdges(), ["ui"], ["db"]))
{
  var edges := strictnessEdges();
  assert edges[0] == Edge("ui", "svc") && edges[1] == Edge("svc", "db");
  assert hasEdge(edges, "ui", "svc");          // witnessed by index 0
  assert hasEdge(edges, "svc", "db");          // witnessed by index 1
  ReachRefl(edges, "ui");
  ReachExtend(edges, "ui", "ui", "svc");       // reach(ui, svc)
  ReachExtend(edges, "ui", "svc", "db");       // reach(ui, db) — the 2-hop laundered path
  assert reach(edges, "ui", "db");
  // No DIRECT ui → db edge: neither of the two edges is ui → db.
  forall k | 0 <= k < |edges| ensures !(edges[k].source == "ui" && edges[k].target == "db") {}
  assert !hasEdge(edges, "ui", "db");
}

// ── Reachability spec + proof scaffolding (hand-written) ───────────────────────────
// Additions only: the `method` bodies below are generated verbatim; predicates,
// lemmas, invariants, decreases and asserts are the hand-written proof. The
// reachability machinery is reused from the xyflow cycle-gate case study.

predicate hasEdge(edges: seq<Edge>, a: string, b: string)
{
  exists i :: 0 <= i < |edges| && edges[i].source == a && edges[i].target == b
}

// A path is a non-empty id-sequence linked by edges. `reach` is reflexive — the
// one-element path witnesses `from ->* from` — matching canReach's reflexive seed.
ghost predicate isPath(edges: seq<Edge>, p: seq<string>)
{
  forall i :: 0 <= i < |p| - 1 ==> hasEdge(edges, p[i], p[i + 1])
}
ghost predicate reach(edges: seq<Edge>, from: string, to: string)
{
  exists p :: |p| >= 1 && p[0] == from && p[|p| - 1] == to && isPath(edges, p)
}

lemma ReachRefl(edges: seq<Edge>, n: string)
  ensures reach(edges, n, n)
{
  assert isPath(edges, [n]);   // witness: the one-element path
}

// Path extension: a path to `mid` followed by an edge mid->next reaches `next`.
lemma ReachExtend(edges: seq<Edge>, from: string, mid: string, next: string)
  requires reach(edges, from, mid)
  requires hasEdge(edges, mid, next)
  ensures reach(edges, from, next)
{
  var p :| |p| >= 1 && p[0] == from && p[|p| - 1] == mid && isPath(edges, p);
  var q := p + [next];
  forall i | 0 <= i < |q| - 1 ensures hasEdge(edges, q[i], q[i + 1]) {
    if i < |p| - 1 {
      assert q[i] == p[i] && q[i + 1] == p[i + 1];
    } else {
      assert q[i] == mid && q[i + 1] == next;
    }
  }
  assert q[0] == from && q[|q| - 1] == next && isPath(edges, q);
}

// A single edge is a (reflexive) reachability — the base of `Domination`.
lemma HasEdgeReach(edges: seq<Edge>, a: string, b: string)
  requires hasEdge(edges, a, b)
  ensures reach(edges, a, b)
{
  assert isPath(edges, [a, b]);
}

// Elements of a filtered sequence come from the original sequence.
lemma FilterIn(f: (Edge ~> bool), xs: seq<Edge>, y: Edge)
  requires forall i :: 0 <= i < |xs| ==> f.requires(xs[i])
  requires y in Std.Collections.Seq.Filter(f, xs)
  ensures y in xs
  decreases |xs|
{
  reveal Std.Collections.Seq.Filter();
  if |xs| > 0 && !(y == xs[0] && f(xs[0])) {
    FilterIn(f, xs[1..], y);
  }
}

// Universe of ids the search can encounter: the source plus all edge endpoints.
ghost function nodeUniverse(edges: seq<Edge>, from: string): set<string>
{
  {from} + (set i | 0 <= i < |edges| :: edges[i].source) + (set i | 0 <= i < |edges| :: edges[i].target)
}

// Forward filter membership: an element satisfying the predicate lands in the result.
lemma FilterContains(f: (Edge ~> bool), xs: seq<Edge>, i: nat)
  requires forall k :: 0 <= k < |xs| ==> f.requires(xs[k])
  requires i < |xs| && f(xs[i])
  ensures xs[i] in Std.Collections.Seq.Filter(f, xs)
  decreases |xs|
{
  reveal Std.Collections.Seq.Filter();
  if i > 0 {
    FilterContains(f, xs[1..], i - 1);
  }
}

// In a visited-set closed under edges, every node of a path from a visited start
// is itself visited (induction along the path prefix).
lemma PathInVisited(edges: seq<Edge>, visited: set<string>, p: seq<string>, k: nat)
  requires isPath(edges, p) && |p| >= 1 && p[0] in visited
  requires forall x :: x in visited ==> forall t :: hasEdge(edges, x, t) ==> t in visited
  requires k < |p|
  ensures p[k] in visited
  decreases k
{
  if k > 0 {
    PathInVisited(edges, visited, p, k - 1);
    assert hasEdge(edges, p[k - 1], p[k]);
  }
}

lemma ClosedReachable(edges: seq<Edge>, from: string, visited: set<string>, y: string)
  requires from in visited
  requires forall x :: x in visited ==> forall t :: hasEdge(edges, x, t) ==> t in visited
  requires reach(edges, from, y)
  ensures y in visited
{
  var p :| |p| >= 1 && p[0] == from && p[|p| - 1] == y && isPath(edges, p);
  PathInVisited(edges, visited, p, |p| - 1);
}

// ── canReach: decides reach EXACTLY (sound + complete + terminating) ────────────────
method canReach(edges: seq<Edge>, from: string, to: string) returns (res: bool)
  // soundness
  ensures (res ==> reach(edges, from, to))
  // completeness
  ensures (reach(edges, from, to) ==> res)
{
  var frontier := [from];
  var visited: seq<string> := [];
  ghost var vset: set<string> := {};   // mirror of `visited` for exact cardinality
  ReachRefl(edges, from);
  while (|frontier| > 0)
    invariant forall x :: x in frontier ==> reach(edges, from, x)
    invariant forall x :: x in frontier ==> x in nodeUniverse(edges, from)
    invariant forall x :: x in vset <==> x in visited
    invariant vset <= nodeUniverse(edges, from)
    // completeness: `from` stays in the search front, `to` is never marked visited,
    // and every visited node's successors are already visited or still queued.
    invariant from in vset || from in frontier
    invariant to !in vset
    invariant forall x :: x in vset ==> forall t :: hasEdge(edges, x, t) ==> (t in vset || t in frontier)
    decreases |nodeUniverse(edges, from) - vset|, |frontier|
  {
    var cur := frontier[0];
    assert cur in nodeUniverse(edges, from);   // cur in frontier ⊆ universe
    frontier := frontier[1..];
    if (cur == to) {
      return true;
    }
    if !((cur in visited)) {
      assert cur in nodeUniverse(edges, from) - vset;   // ⇒ the difference strictly shrinks
      visited := (visited + [cur]);
      vset := vset + {cur};                    // cur ∉ vset (guard) ⇒ |universe - vset| drops by 1
      var succ := (var s_map := Std.Collections.Seq.Filter((e: Edge) => (e.source == cur), edges); seq(|s_map|, i_map requires 0 <= i_map < |s_map| => var e := s_map[i_map]; e.target));
      // `out` mirrors the comprehension's let-bound receiver. succ[j] == out[j].target
      // holds because the comprehension indexes a VARIABLE (s_map), so Dafny's index
      // axiom fires — it would not over an inlined `Filter(..)` (§8.6 E2).
      ghost var out := Std.Collections.Seq.Filter((e: Edge) => (e.source == cur), edges);
      // succ elements are targets of cur's out-edges: reachable, and in the universe.
      forall x | x in succ
        ensures reach(edges, from, x) && x in nodeUniverse(edges, from)
      {
        var j :| 0 <= j < |succ| && succ[j] == x;
        assert out[j].source == cur && out[j].target == x;
        FilterIn((e: Edge) => (e.source == cur), edges, out[j]);
        assert hasEdge(edges, cur, x);
        ReachExtend(edges, from, cur, x);
      }
      // succ contains EVERY out-neighbour of cur — keeps the closure invariant.
      forall t | hasEdge(edges, cur, t)
        ensures t in succ
      {
        var i :| 0 <= i < |edges| && edges[i].source == cur && edges[i].target == t;
        FilterContains((e: Edge) => (e.source == cur), edges, i);
        var j :| 0 <= j < |out| && out[j] == edges[i];
        assert succ[j] == out[j].target == t;
      }
      frontier := (frontier + succ);
    }
  }
  // frontier is empty ⇒ vset is closed under edges and contains `from`. A path
  // from->*to would then force `to in vset`, contradicting `to !in vset`.
  assert frontier == [];
  assert from in vset;
  if reach(edges, from, to) {
    assert forall x :: x in vset ==> forall t :: hasEdge(edges, x, t) ==> t in vset;
    ClosedReachable(edges, from, vset, to);
  }
  return false;
}

// ── reachesAny: reach to a SET, decided exactly ────────────────────────────────────
method reachesAny(edges: seq<Edge>, from: string, sinks: seq<string>) returns (res: bool)
  // soundness / completeness: decides reach-to-set exactly
  ensures (res ==> exists j: int :: (((0 <= j) && (j < |sinks|)) && reach(edges, from, sinks[j])))
  ensures ((exists j: int :: (((0 <= j) && (j < |sinks|)) && reach(edges, from, sinks[j]))) ==> res)
{
  var i := 0;
  while (i < |sinks|)
    invariant 0 <= i <= |sinks|
    invariant forall k :: 0 <= k < i ==> !reach(edges, from, sinks[k])
    decreases |sinks| - i
  {
    var i_t0 := canReach(edges, from, sinks[i]);
    if i_t0 {
      assert reach(edges, from, sinks[i]);     // canReach sound ⇒ witness j = i
      return true;
    }
    assert !reach(edges, from, sinks[i]);      // canReach complete ⇒ no path to sinks[i]
    i := (i + 1);
  }
  return false;
}

// ── violates: decide a forbidden-reach constraint exactly ───────────────────────────
// res ⟺ some `sources` module reaches some `sinks` module (through any chain).
method violates(edges: seq<Edge>, sources: seq<string>, sinks: seq<string>) returns (res: bool)
  // soundness / completeness: decides "any source reaches any sink" exactly
  ensures (res ==> exists i: int, j: int :: (((((0 <= i) && (i < |sources|)) && (0 <= j)) && (j < |sinks|)) && reach(edges, sources[i], sinks[j])))
  ensures ((exists i: int, j: int :: (((((0 <= i) && (i < |sources|)) && (0 <= j)) && (j < |sinks|)) && reach(edges, sources[i], sinks[j]))) ==> res)
{
  var i := 0;
  while (i < |sources|)
    invariant 0 <= i <= |sources|
    invariant forall ip, j :: 0 <= ip < i && 0 <= j < |sinks| ==> !reach(edges, sources[ip], sinks[j])
    decreases |sources| - i
  {
    var i_t1 := reachesAny(edges, sources[i], sinks);
    if i_t1 {
      ghost var j :| 0 <= j < |sinks| && reach(edges, sources[i], sinks[j]);   // from reachesAny soundness
      assert 0 <= i < |sources| && 0 <= j < |sinks| && reach(edges, sources[i], sinks[j]);
      return true;
    }
    assert forall j :: 0 <= j < |sinks| ==> !reach(edges, sources[i], sinks[j]);   // reachesAny completeness
    i := (i + 1);
  }
  return false;
}

// ── Witness validation (the certifying-algorithm half) ──────────────────────────────
// The untrusted shell searches for a candidate laundering chain; these verified
// functions vouch for it. `edgeExists` decides a single edge; `checkChain` confirms a
// whole candidate is a genuine import path from `from` to a forbidden sink — so any
// chain that reaches the lint message is proof-carrying.

method edgeExists(edges: seq<Edge>, a: string, b: string) returns (res: bool)
  // soundness
  ensures (res ==> hasEdge(edges, a, b))
  // completeness
  ensures (hasEdge(edges, a, b) ==> res)
{
  var i := 0;
  while (i < |edges|)
    invariant 0 <= i <= |edges|
    invariant forall k :: 0 <= k < i ==> !(edges[k].source == a && edges[k].target == b)
    decreases |edges| - i
  {
    if ((edges[i].source == a) && (edges[i].target == b)) {
      return true;
    }
    i := (i + 1);
  }
  return false;
}

method checkChain(edges: seq<Edge>, chain: seq<string>, from: string, sinks: seq<string>) returns (res: bool)
  // soundness: a validated chain is a real import path from `from` to a forbidden sink.
  ensures (res ==> ((((|chain| >= 1) && (chain[0] == from)) && isPath(edges, chain)) && exists j: int :: (((0 <= j) && (j < |sinks|)) && (chain[(|chain| - 1)] == sinks[j]))))
{
  if (|chain| == 0) {
    return false;
  }
  if (chain[0] != from) {
    return false;
  }
  if !((chain[(|chain| - 1)] in sinks)) {
    return false;
  }
  var i := 0;
  while (i < (|chain| - 1))
    invariant 0 <= i <= |chain| - 1
    invariant forall k :: 0 <= k < i ==> hasEdge(edges, chain[k], chain[k + 1])
    decreases |chain| - 1 - i
  {
    var i_t2 := edgeExists(edges, chain[i], chain[(i + 1)]);
    if !(i_t2) {
      return false;
    }
    assert hasEdge(edges, chain[i], chain[i + 1]);   // edgeExists soundness
    i := (i + 1);
  }
  assert isPath(edges, chain);   // every consecutive pair is an edge
  return true;
}

// ── Verified witness CONSTRUCTION: findReachPath ────────────────────────────────────
// A path-carrying BFS. The frontier holds whole paths; a ghost `ends` mirrors their
// endpoints so the completeness/termination argument reduces to canReach's (over the
// node set `ends`), while path validity is carried directly. Returns a real witness
// path whenever a sink is reachable, [] otherwise — sound AND complete.

// Append one node to a path along a real edge — the result is still a path.
lemma PathSnoc(edges: seq<Edge>, p: seq<string>, t: string)
  requires |p| >= 1 && isPath(edges, p) && hasEdge(edges, p[|p| - 1], t)
  ensures |p + [t]| >= 1 && (p + [t])[0] == p[0] && (p + [t])[|p + [t]| - 1] == t && isPath(edges, p + [t])
{
  var q := p + [t];
  forall i | 0 <= i < |q| - 1 ensures hasEdge(edges, q[i], q[i + 1]) {
    if i < |p| - 1 {
      assert q[i] == p[i] && q[i + 1] == p[i + 1];
    } else {
      assert q[i] == p[|p| - 1] && q[i + 1] == t;
    }
  }
}

method findReachPath(edges: seq<Edge>, from: string, sinks: seq<string>) returns (res: seq<string>)
  // soundness: a non-empty result is a real witness path from `from` to a sink
  ensures ((|res| > 0) ==> (((res[0] == from) && isPath(edges, res)) && exists j: int :: (((0 <= j) && (j < |sinks|)) && (res[(|res| - 1)] == sinks[j]))))
  // completeness: an empty result means no sink is reachable
  ensures ((|res| == 0) ==> !(exists j: int :: (((0 <= j) && (j < |sinks|)) && reach(edges, from, sinks[j]))))
{
  var frontier := [[from]];
  var visited: seq<string> := [];
  ghost var ends: seq<string> := [from];     // ends[k] == endpoint of frontier[k]
  ghost var vset: set<string> := {};
  while (|frontier| > 0)
    invariant |ends| == |frontier|
    invariant forall k :: 0 <= k < |frontier| ==> |frontier[k]| >= 1 && ends[k] == frontier[k][|frontier[k]| - 1]
    invariant forall k :: 0 <= k < |frontier| ==> frontier[k][0] == from && isPath(edges, frontier[k])
    invariant forall x :: x in ends ==> x in nodeUniverse(edges, from)
    invariant forall x :: x in vset <==> x in visited
    invariant vset <= nodeUniverse(edges, from)
    invariant from in vset || from in ends
    invariant forall j :: 0 <= j < |sinks| ==> sinks[j] !in vset
    invariant forall x :: x in vset ==> forall t :: hasEdge(edges, x, t) ==> (t in vset || t in ends)
    decreases |nodeUniverse(edges, from) - vset|, |frontier|
  {
    ghost var entryEnds := ends;
    ghost var entryVset := vset;
    var p := frontier[0];
    assert |p| >= 1 && p[0] == from && isPath(edges, p);        // path-validity (k = 0)
    assert entryEnds[0] == p[|p| - 1];                          // linkage (k = 0)
    assert entryEnds[0] in nodeUniverse(edges, from);
    frontier := frontier[1..];
    ends := ends[1..];
    var cur := p[(|p| - 1)];
    assert cur == entryEnds[0];
    // when cur is a sink, p is a path from `from` ending at a sink — return it
    if (cur in sinks) {
      return p;
    }
    if !((cur in visited)) {
      assert cur !in vset;
      assert cur in nodeUniverse(edges, from) - vset;           // ⇒ the difference strictly shrinks
      visited := (visited + [cur]);
      vset := vset + {cur};
      var extended := (var s_map := Std.Collections.Seq.Filter((e: Edge) => (e.source == cur), edges); seq(|s_map|, i_map requires 0 <= i_map < |s_map| => var e := s_map[i_map]; (p + [e.target])));
      // `out` mirrors the comprehension's let-bound receiver; extended[k] == p + [out[k].target]
      // holds because the comprehension indexes a VARIABLE (s_map) — §8.6 E2.
      ghost var out := Std.Collections.Seq.Filter((e: Edge) => (e.source == cur), edges);
      ghost var succ := Std.Collections.Seq.Map((e: Edge) => e.target, out);
      // every extended path is valid, ends at cur's out-neighbour succ[k], in the universe
      forall k | 0 <= k < |extended|
        ensures |extended[k]| >= 1 && extended[k][0] == from && isPath(edges, extended[k])
                && extended[k][|extended[k]| - 1] == succ[k] && succ[k] in nodeUniverse(edges, from)
      {
        assert extended[k] == p + [out[k].target];              // seq comprehension
        assert succ[k] == out[k].target;                        // Map
        FilterIn((e: Edge) => (e.source == cur), edges, out[k]);
        assert hasEdge(edges, cur, out[k].target);
        PathSnoc(edges, p, out[k].target);
      }
      // succ contains EVERY out-neighbour of cur — keeps the closure invariant
      forall t | hasEdge(edges, cur, t)
        ensures t in succ
      {
        var m :| 0 <= m < |edges| && edges[m].source == cur && edges[m].target == t;
        FilterContains((e: Edge) => (e.source == cur), edges, m);
        var k :| 0 <= k < |out| && out[k] == edges[m];
        assert succ[k] == out[k].target == t;
      }
      ends := ends + succ;
      frontier := (frontier + extended);
      // linkage + path-validity for the new frontier
      assert forall k :: 0 <= k < |frontier| ==>
        |frontier[k]| >= 1 && ends[k] == frontier[k][|frontier[k]| - 1] && frontier[k][0] == from && isPath(edges, frontier[k]);
      // re-establish the closure invariant: every visited node's successor is visited or queued
      assert entryEnds == [entryEnds[0]] + entryEnds[1..];
      forall x | x in vset
        ensures forall t :: hasEdge(edges, x, t) ==> (t in vset || t in ends)
      {
        forall t | hasEdge(edges, x, t)
          ensures t in vset || t in ends
        {
          if x == cur {
            assert t in succ;                                   // out-neighbour of cur ⇒ in succ ⊆ ends
          } else {
            assert x in entryVset;                              // x ∈ vset = entryVset ∪ {cur}, x ≠ cur
            if !(t in entryVset) {
              assert t in entryEnds;                            // entry closure invariant
              if t == entryEnds[0] {
                assert t == cur;                                // entryEnds[0] = cur ⇒ t ∈ vset
              } else {
                assert t in entryEnds[1..];                     // ⊆ ends
              }
            }
          }
        }
      }
    }
  }
  // frontier empty ⇒ ends empty ⇒ vset closed under edges and contains `from`.
  assert |ends| == 0;
  assert from in vset;
  assert forall x :: x in vset ==> forall t :: hasEdge(edges, x, t) ==> t in vset;
  forall j | 0 <= j < |sinks| ensures !reach(edges, from, sinks[j]) {
    if reach(edges, from, sinks[j]) {
      ClosedReachable(edges, from, vset, sinks[j]);             // ⇒ sinks[j] ∈ vset, contradicts the invariant
    }
  }
  return [];
}

// ── The headline meta-theorem: we STRICTLY DOMINATE one-hop checking ────────────────
// `directViolation` is what every incumbent linter decides: a DIRECT source→sink
// import edge. `reachViolation` is the true property `violates` decides: a source
// REACHES a sink through any chain.

ghost predicate directViolation(edges: seq<Edge>, sources: seq<string>, sinks: seq<string>)
{
  exists i, j :: 0 <= i < |sources| && 0 <= j < |sinks| && hasEdge(edges, sources[i], sinks[j])
}

ghost predicate reachViolation(edges: seq<Edge>, sources: seq<string>, sinks: seq<string>)
{
  exists i, j :: 0 <= i < |sources| && 0 <= j < |sinks| && reach(edges, sources[i], sinks[j])
}

// The existential meta-theorem (derived from the concrete witness `strictness`,
// whose statement is surfaced in core.verified.ts and proved in strictness_ensures).
lemma Strictness()
  ensures exists edges: seq<Edge>, sources: seq<string>, sinks: seq<string> ::
            reachViolation(edges, sources, sinks) && !directViolation(edges, sources, sinks)
{
  strictness_ensures();
  assert reachViolation(strictnessEdges(), ["ui"], ["db"]) && !directViolation(strictnessEdges(), ["ui"], ["db"]);
}
